# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Authors of API-Speculator

database:
  uri: <mongoDBUri>
  user: <user>
  password: <password>
  name: <databaseName>
  collection: <collectionName>

environment:
  clusterId: <yourClusterId>
  tenantId: <yourTenantId>

openAPISpec: <urlOrPath> # Either filepath or URL

exporter:
  jsonReportFilePath: report.json

scanName: default-openapi-spec-scan  

apiCollections:
  # The MongoDB collection name pattern (weâ€™ll replace <tenant_id> dynamically)
  collectionTemplate: "obs_system_api_collections_<tenant_id>"

  # List of collection names we want to use
  nameList:
    - "collection-1"
    - "collection-2"    

endpoints:
  - "endpoint-1"
  - "endpoint-2"
