# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Authors of API-Speculator

database:
  uri: <mongoDBUri>
  user: <user>
  password: <password>
  name: <databaseName>
  collection: <collectionName>

environment:
  clusterId: <yourClusterId>
  tenantId: <yourTenantId>

openAPISpecs:
  # List of OpenAPI specs (Either filepath or URL)
  - <urlOrPath1>
  - <urlOrPath2>

exporter:
  jsonReportFilePath: report.json

scanName: default-openapi-spec-scan  

apiCollections:
  # The MongoDB collection name used for storing API collections
  dbCollectionName: <collectionName>

  # List of API collection names to be used for the scan
  collectionNames:
    - "collection-1"
    - "collection-2"    

endpoints:
  - "endpoint-1"
  - "endpoint-2"